gkres/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views


urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path('', include('tennis.urls', namespace='tennis')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

tennis/urls.py
from django.urls import path
from .views import tennis_tournaments, tournament

app_name = 'tennis'

urlpatterns = [
    path('tennis-tournaments/', tennis_tournaments, name="tennis-tournaments"),
    path('tournament/<int:pk>', tournament, name='tournament')
]

gkres/templates/tags/footer.html
{% load static wagtailcore_tags wagtailimages_tags base_tags %}

{% get_site_root as site_root %}

<div class="footer" id="footer">
    <div class="footer-logo">
        <a href="/">
            <img src="{% static 'images/logo.png' %}" alt="logo.png" class="logo">
        </a>
    </div>
    <div class="footer-content">
        
    </div>
</div>

gkres/templates/tags/header.html
{% load static wagtailcore_tags wagtailimages_tags base_tags %}

{% get_site_root as site_root %}

<div class="header" id="header">
    <div class="header-icons">
        <a href="/" class="heder-logo">
            <img src="{% static 'images/logo.png' %}" alt="logo.png" class="logo">
        </a>
    </div>

    {% top_menu parent=site_root calling_page=self %}
</div>

gkres/templates/tags/top_menu.html
{% load base_tags wagtailcore_tags %}
{% get_site_root as site_root %}

<div class="header-menu">
    <ul class="menu-list">
        <li class="menu-item"><a href="/" class="menu-link">Главная</a></li>

        {% for menuitem in menuitems %}
            {% if menuitem.show_dropdown %}
                <li class="menu-item">
                    <div class="dropdown-container">
                        <a href="{% pageurl menuitem %}" class="menu-link" id="btn">
                            {{ menuitem.title }}
                        </a>
                        <a href="##" class="dropdown-link">
                            <i class="fa fa-bars fa-dropdown" id="arrow"></i>
                        </a>
                    </div>
                    <div class="dropdown" id="dropdown">
                        {% top_menu_children parent=menuitem %}
                    </div>
                </li>
            {% else %}
                <li class="menu-item"><a href="{% pageurl menuitem %}" class="menu-link">{{ menuitem.title }}</a></li>
            {% endif %}
        {% endfor %}

        {% for service in home_services %}
            {% if service.is_menu %}
                <li class="menu-item"><a href="{{ service.link }}" class="menu-link">{{ service.title }}</a></li>
            {% endif %}
        {% endfor %}

        {% for service in account_services %}
            {% if service.is_menu %}
                <li class="menu-item"><a href="{{ service.link }}" class="menu-link">{{ service.title }}</a></li>
            {% endif %}
        {% endfor %}

        <!-- {% if request.user.is_authenticated %}
            <li class="menu-item">
                <a href="{% url 'tennis:tennis-tournaments' %}" class="menu-link">
                    <span class="icon">
                        <i class="icon-trophy"></i>
                    </span>
                    Теннисный турнир
                </a>
            </li>
        {% endif %} -->
    </ul>
</div>

gkres/templates/tags/top_menu_children.html
{% load base_tags wagtailcore_tags %}

{% for child in menuitems_children %}
    <div class="dropdown-item">
        <i class="fa fa-code-fork"></i>
        <a href="{% pageurl child %}" class="menu-link">{{ child.title }}</a>
    </div>
{% endfor %}

gkres/templates/tags/user_header.html
{% load static wagtailcore_tags wagtailimages_tags base_tags %}

{% get_site_root as site_root %}

<div class="user_header">
    <form action="{% url 'search' %}" method="get" class="search">
        <input name="query" class="search-field" {% if search_query %} value="{{ search_query }}"{% endif %}>
        <button class="search-button"><i class="fa fa-search"></i></button>
    </form>
    {% if request.user.is_authenticated %}
        <div class="account">
            <a href="https://lk.gkres.ru/admin/logout/?next=/">
                <p>{{ request.user.first_name }} {{ request.user.last_name }}</p>
            </a> 
        </div>
    {% else %}
        <div class="account">
            <a href="https://lk.gkres.ru">
                <i class="fa fa-user-circle"></i>
            </a> 
        </div>
    {% endif %}
</div>