gkres/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views


urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path('', include('tennis.urls', namespace='tennis')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

tennis/urls.py
from django.urls import path
from .views import tennis_tournaments, tournament

app_name = 'tennis'

urlpatterns = [
    path('tennis-tournaments/', tennis_tournaments, name="tennis-tournaments"),
    path('tournament/<int:pk>', tournament, name='tournament')
]

tennis/models.py
from random import choices
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import m2m_changed, post_save
from django.dispatch import receiver


class Tournaments(models.Model):
    name = models.CharField(
        max_length = 100,
        blank = False,
        unique=True,
        verbose_name = 'Название турнира',
    )
    date = models.DateTimeField(
        default = timezone.now,
        verbose_name = 'Дата и время начала турнира'
    )
    players = models.ManyToManyField(
        'Players',
        verbose_name = "Участники",
    )
    tour_format = models.CharField(
        max_length = 50,
        blank = False,
        choices = [
            ('круговая', 'круговая'),
            ('плей-офф', 'плей-офф')    
        ],
        verbose_name = 'Формат проведения',
        default = 'круговая',
    )
    win_score = models.IntegerField(
        null = False,
        blank = False,
        default = 1,
        verbose_name = 'Количество очков за победу'
    )
    lose_score = models.IntegerField(
        null = False,
        blank = False,
        default = 0,
        verbose_name = 'Количество очков за поражение не в 0',
        help_text = 'Оставить 0 при стандартном ведении счета'
    )
    image = models.ImageField(
        upload_to = 'images/',
        blank = True,
        null = True,
        verbose_name = 'Изображение для окончания турнира'
    )
    is_end = models.BooleanField(
        default = False,
        verbose_name = 'Закончился турнир?'
    )
    f_place = models.CharField(
        max_length=200,
        null = True,
        blank = True,
        verbose_name='Первое место'
    )
    s_place = models.CharField(
        max_length=200,
        null = True,
        blank = True,
        verbose_name='Второе место'
    )
    th_place = models.CharField(
        max_length=200,
        null = True,
        blank = True,
        verbose_name='Третье место место'
    )
    
    def __str__(self):
        return self.name  


class Games(models.Model):
    tournament = models.ForeignKey(
        'Tournaments',
        on_delete = models.CASCADE,
        unique=False,
        verbose_name = 'Игра турнира',
    )
    date = models.DateTimeField(
        blank = True,
        null = True,
        verbose_name = 'Дата и время проведения игры'
    )
    player_one = models.CharField(
        max_length = 100,
        blank = False,
        verbose_name = 'Первый игрок',
        default = '-'
    )
    player_two = models.CharField(
        max_length = 100,
        blank = False,
        verbose_name = 'Второй игрок',
        default = '-'
    )
    player_one_score = models.IntegerField(
        default = 0,
        blank = False,
        null = False,
        verbose_name = f'Результат первого игрока'
    )
    player_two_score = models.IntegerField(
        default = 0,
        blank = False,
        null = False,
        verbose_name = 'Результат второго игрока'
    )
    set_statistic = models.CharField(
        max_length = 100,
        default = '0/0, 0/0',
        blank = False,
        null = False,
        verbose_name = 'Счет по геймам'
    )
    
    class Meta:
        verbose_name = f'Игра'
        verbose_name_plural = f'Игры'  
        
    def __str__(self):
        return f'Игра(ы) №{self.pk}'  


class Players(models.Model):
    player = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        verbose_name = 'Участники',
    )
    
    def __str__(self):
        return f'{self.player.first_name} {self.player.last_name}'


def create_games(sender, instance, **kwargs):
    tour_players_query = instance.players.all()
    tour_players = [f'{player}' for player in tour_players_query]

    games = [[tour_players[i], tour_player] for tour_player in tour_players for i in range(len(tour_players) - 1)]
    [games.remove(j) for j in games if j[0] == j[1]]

    for k in games:
        for l in games:
            if l[0] + l[1] == k[1] + k[0]:
                games.remove(l)

    for game in games:
        Games.objects.create(
            tournament = instance,
            player_one = game[0],
            player_two = game[1],
        )
    

m2m_changed.connect(create_games, sender=Tournaments.players.through)

tennis/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Tournaments, Games, Players
from datetime import datetime
from django.db.models import Q
import re


def mobile(request):
    MOBILE_AGENT_RE=re.compile(r".*(iphone|mobile|androidtouch)",re.IGNORECASE)

    if MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        return True
    else:
        return False


# TODO: Переделать функции заполнения таблиц в одну и оптимизировать запросы
def fill_table_pc(games, players, win_score, lose_score):
    # итоговая таблица с данными
    table = {}
    for player in players:
        # пустой список для каждого игрока для будущего наполнения
        table[f'{player}'] = []
        # счетчик очков
        player_score = 0   
             
        for i in range(len(players)):
            # если игроки совпадают
            if player == players[i]:
                table[f'{player}'].append(f'-')
            # если нет
            else:
                for game in games.values():
                    # фильтруем на повторы и добавляем счет
                    if f'{player}:{players[i]}' == f'{game["player_one"]}:{game["player_two"]}':
                        table[f'{player}'].append(f'{game["player_one_score"]} - {game["player_two_score"]}')
                        
                        # итоговое кол-во очков за каждую победу
                        if game["player_one_score"] > game["player_two_score"] and game["player_two_score"] == 0:
                            player_score += win_score
                        elif game["player_one_score"] > game["player_two_score"] and game["player_two_score"] != 0:
                            player_score += win_score - lose_score
                        elif game["player_one_score"] < game["player_two_score"] and game["player_one_score"] != 0:
                            player_score += lose_score
                        
                    elif f'{player}:{players[i]}' == f'{game["player_two"]}:{game["player_one"]}':
                        # set_stat = ', '.join(game["set_statistic"][::-1].split(',')[::-1])[:-1]
                                        
                        table[f'{player}'].append(f'{game["player_two_score"]} - {game["player_one_score"]}')

                        if game["player_two_score"] > game["player_one_score"] and game["player_one_score"] == 0:
                            player_score += win_score
                        elif game["player_two_score"] > game["player_one_score"] and game["player_one_score"] != 0:
                            player_score += win_score - lose_score
                        elif game["player_two_score"] < game["player_one_score"] and game["player_two_score"] != 0:
                            player_score += lose_score
        
        table[f'{player}'].append(player_score)

    return table


def fill_table_mobile(games, players, win_score, lose_score):
    table = {}
    
    for player in players:
        table[f'{player}'] = []
        player_score = 0
        
        for i in range(len(players)):
            if player != players[i]:
                for game in games.values():
                    # фильтруем на повторы и добавляем счет
                    if f'{player}:{players[i]}' == f'{game["player_one"]}:{game["player_two"]}':
                        table[f'{player}'].append((players[i], f'{game["player_one_score"]} - {game["player_two_score"]}'))
                        
                        # итоговое кол-во очков за каждую победу
                        if game["player_one_score"] > game["player_two_score"] and game["player_two_score"] == 0:
                            player_score += win_score
                        elif game["player_one_score"] > game["player_two_score"] and game["player_two_score"] != 0:
                            player_score += win_score - lose_score
                        elif game["player_one_score"] < game["player_two_score"] and game["player_one_score"] != 0:
                            player_score += lose_score
                                
                    elif f'{player}:{players[i]}' == f'{game["player_two"]}:{game["player_one"]}':
                        table[f'{player}'].append((players[i], f'{game["player_two_score"]} - {game["player_one_score"]}'))
                        
                        if game["player_two_score"] > game["player_one_score"] and game["player_one_score"] == 0:
                            player_score += win_score
                        elif game["player_two_score"] > game["player_one_score"] and game["player_one_score"] != 0:
                            player_score += win_score - lose_score
                        elif game["player_two_score"] < game["player_one_score"] and game["player_two_score"] != 0:
                            player_score += lose_score
        
        table[f'{player}'].append(('Количество очков:', player_score))
    
    return table


def tennis_tournaments(request):
    context = {}
    tours = Tournaments.objects.all()
    context['tours'] = tours
    context['now'] = datetime.now()
    context['user'] = request.user
    
    return render(request, 'tennis/tournaments.html', context=context)


def tournament(request, pk):
    context = {}
    
    tour = Tournaments.objects.get(pk=pk)
    context['tour'] = tour
    
    win_score = tour.win_score
    lose_score = tour.lose_score
    
    games = Games.objects.filter(tournament=tour)
    context['games'] = games
    
    players = tour.players.all()
    # context['players'] = players
    # context['players_count'] = range(len(players))
    
    # нужно для перерисовки таблиц под мобильные устройства
    if mobile(request):
        is_mobile = True
        table_mobile = fill_table_mobile(games, players, win_score, lose_score)
        context['table_mobile'] = table_mobile
    else:
        is_mobile = False   
        table_pc = fill_table_pc(games, players, win_score, lose_score)
        context['table_pc'] = table_pc
        
    context['is_mobile'] = is_mobile
    
    return render(request, 'tennis/tour.html', context=context)

tennis/templates/tennis/tour.html
{% extends 'base.html' %}
{% load static %}
{% load wagtailcore_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/tour.css' %}">
{% endblock %}

{% block title %}
    {{ tour.name }}
{% endblock %}

{% block content %}
    <section id="tennis">
        {% if tour.is_end %}
            {% if tour.image %}
                <div class="tennis_bg" style="background-image: url(../../../media/{{tour.image}});"></div>
            {% endif %}
        {% else %}
	        <div class="tennis_bg"></div>
        {% endif %}
        <div style="margin: 0 auto 20px auto; text-align: center;">
            <h1 style="margin-bottom: 50px; color: white; text-shadow: 2px 0 2px #000, 0 2px 2px #000, -2px 0 2px #000, 0 -2px 2px #000;">{{ tour.name }}</h1>
        </div>

        {% if tour.is_end %}
            <div style="margin: 200px auto 20px auto; text-align: center;">
                <h1 style="margin-bottom: 50px; color: white; text-shadow: 2px 0 2px #000, 0 2px 2px #000, -2px 0 2px #000, 0 -2px 2px #000;">Первое место:<br>{{ tour.f_place }}</h1>
            </div>
            <div style="margin: 0 auto 20px auto; text-align: center;">
                <h1 style="margin-bottom: 50px; color: white; text-shadow: 2px 0 2px #000, 0 2px 2px #000, -2px 0 2px #000, 0 -2px 2px #000;">Второе место:<br>{{ tour.s_place }}</h1>
            </div>
            <div style="margin: 0 auto 20px auto; text-align: center;">
                <h1 style="margin-bottom: 50px; color: white; text-shadow: 2px 0 2px #000, 0 2px 2px #000, -2px 0 2px #000, 0 -2px 2px #000;">Третье место:<br>{{ tour.th_place }}</h1>
            </div>
        {% else %}
            {% if games %}
                {% if not is_mobile %}
                    <div style="max-width: 1500px; margin: 0 auto;">
                        <table class="simple-little-table" cellspacing="0">
                            <tr>
                                <th>Игроки</th>

                                {% for key in table_pc.keys %}
                                    <th style="text-align: center;">{{ key }}</th>
                                {% endfor %}

                                <th>Очки</th>
                            </tr>

                            {% for key, value in table_pc.items %}
                                <tr>
                                    <td>
                                        {{ key }}
                                    </td>

                                    {% for v in value %}
                                        {% if v == '-' %}
                                            <td style="background: rgba(69, 69, 69, 0.433);"></td>
                                        {% elif v == '0 - 0' %}
                                            <td> - </td>
                                        {% else %}
                                            <td style="text-align: center;">
                                                {{ v }}
                                            </td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                {% else %}
                    {% for key, value in table_mobile.items %}
                        <div style="max-width: 1400px; margin: 0 auto;">
                            <table class="simple-little-table" cellspacing="0">
                                <tr>
                                    <th>Игроки</th>
                                    <th style="text-align: center;">{{ key }}</th>
                                </tr>

                                {% for v in value %}
                                    <tr>
                                        <td>
                                            {{ v.0 }}
                                        </td>
                                        <td>
                                            {{ v.1 }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    {% endfor %}
                {% endif %}
            {% else %}
                <div style="margin: 0 auto 20px auto; text-align: center;">
                    <h1 style="margin-top: 200px; color: rgb(179, 76, 76)">Игры еще не назначены</h1>
                </div>
            {% endif %}
        </section>

        {% if games %}
            <section id="testimonials">
                <div class="row">
                    <div class="col-twelve">
                        <h2>Предстоящие игры</h2>
                    </div>   		
                </div>   	
                <div class="row flex-container">
                    <div id="testimonial-slider" class="flex-slider animate-this">
                        <ul class="slides">
                            {% for game in games %}
                                {% if game.date and game.player_one_score == 0 and game.player_two_score == 0 %}
                                    <li>
                                        <div class="testimonial-author">
                                            <div class="author-info">
                                                <span class="position">
                                                    На этой неделе
                                                </span>
                                                {{ game.player_one }} - {{ game.player_two }}
                                                <br>
                                            </div>
                                        </div>                 
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>        
                </div>
            </section>
        {% endif %}
    {% endif %}
{% endblock %}

tennis/templates/tennis/tournaments.html
{% extends 'base.html' %}
{% load static %}
{% load wagtailcore_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/tournaments.css' %}">
{% endblock %}

{% block title %}
    Список турниров
{% endblock %}

{% block content %}
    <section id="tennis">
        <div class="overlay"></div>
        <div class="gradient-overlay"></div>

        <div class="row narrow section-intro with-bottom-sep animate-this">
            <div class="col-full">
                <div class="lead">
                    <h1>Список турниров по теннису</h1>
                </div>

            </div>
        </div>

        <div class="row tennis-content">
            <div class="tennis-list block-1-2 block-tab-full group">
                {% for tour in tours %}
                    <div class="bgrid service-item animate-this">
                        <a class="" href="{% url 'tennis:tournament' tour.pk %}">
                            <span class="icon">
                                <i class="icon-trophy"></i>
                            </span>	              
                            <div class="service-content border-block">
                                <h3 class="h05">{{ tour.name }}</h3>
                                <p>Формат сетки: {{ tour.tour_format }}</p>
                                {% if tour.is_end is not None %}
                                    {% if now|date:'dmy' < tour.date|date:'dmy' %}
                                        <p style="color: rgb(245, 182, 171)">Начнется {{ tour.date }}</p>
                                    {% else %}
                                        <p style="color: rgb(218, 245, 171)">Проходит в данный момент</p>
                                    {% endif %}
                                {% else %}
                                    <p style="color: rgb(245, 182, 171)">Турнир окончен!</p>
                                {% endif %}
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>                                
{% endblock %}